### ISSUE TITLE
How to use bettercap with fake ap enabled?

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#106]
## What's the problem (or question)?

*hi, does the sslstrip work? i can only get the credentials for non https sites. i have enabled the plugins. When i use bettercap it can strip certain sites like hotmail.com, mail.com by adding "wwww". does wifi-pumpkin does the same?

Also like to comment that the gui interface of wifi-pumpkin is really nice and well done*
#### Please tell us details about your environment.
- Card wireless adapters name (please check if support AP/mode): TL-WN722N
- Version used tool: 0.8.3
- Virtual Machine (yes or no and which): no
- Operating System and version: Parrot Security Os

**Comment by mh4x0f** [comment]
hi, the sslstrip not work for all website, because HSTS implementation,if you want to use WiFi-Pumpkin + Bettercap you need to disable plugins for this you should go in to Plugins tab and uncheck the option Enable Proxy Server as can see in screenshot bellow.
![screenshot_kali35](https://cloud.githubusercontent.com/assets/6795613/19778145/b7f32d9c-9c51-11e6-9c11-7ac120d229ea.png)

just open new terminal and run bettercap (using -I options ) with same the interface (wlanX) that you set for mount AP in WiFi-Pumpkin. 
ex: 
if you are using interface (wlanX) for mount AP in WiFi-Pumpkin then you need to specify this interface in bettercap check-out ...

> sudo bettercap -I wlanX -X

**Comment by jeretc** [comment]
Ok , thanks for the info.
