### ISSUE TITLE
web cloner becomes non-responsive

### ISSUE THREAD

**Issue by denux** [P0cL4bs/WiFi-Pumpkin-deprecated#124]
-I created a beef hook and in DNS spoof module, I then select a target.
-i phishing manager I paste my hook and want to open facebook login with hook when targets opens example.com as domain.
-but the phishing manager stops responding, I have tried multiple combinations it works when i use index.html but becomes non-responsive on choosing website clone and entering "facebook.com/login" or other links.
-and I cant understand how will injector proxy (selected as beef hook) works,activity manager in wifi-pumpkin does shows hooked in links but there is no sessions in BeEF.

PS. my objective is that when someone connects to the AP, he can surf the net as it is (or maybe without ssl using sslstrip), while doing so every link he opens in the browser is connected to the beef hook. I tried every possible combination of settings along with almost every other method online, but can't make it work.

Hope you will look to it soon.
Thank you.

**Comment by mh4x0f** [comment]
look [bug reppoting](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

**Comment by mh4x0f** [comment]
@denux I don't find any problem with this module, i try in my lab with different OS and all working fine.The phishing module  is crashing  because you finishing the connection with clients connected  the HTTP server can't finish the process and return a error in terminal. I can you help better if you read the bug report and follow all steps that you can see there.

 PS: the module dns spoof only work with Proxy server disabled.

**Comment by jeretc** [comment]
i made a fake-portal to go with wifi-pumpkin. have tested it and works well. i used these modules in wifi-pumpkin, DNS Spoof and Phising Manager with the Rogue AP. if you ever want to try it out ..

https://github.com/jeretc/fake-portal
