### ISSUE TITLE
Pumpkin setup v8.0.4 settings

### ISSUE THREAD

**Issue by MicheleLearning** [P0cL4bs/WiFi-Pumpkin-deprecated#179]
## What's the problem (or question)?

*After the completion of setting up wifi-pumpkin - I look to modify the settings and I notice that I do not have any network adapters listed for me to select.  Not sure what I did wrong if this is tied to the configuration of the VM or within wifi-pumpkin.  Could someone help me?  I have attached a screenshot of the setup screen with the no network adapters to select
![screenshot from 2017-01-18 11-37-27](https://cloud.githubusercontent.com/assets/25204905/22073473/6bfbee0c-dd73-11e6-8e00-9ef4388898a8.png)
*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: **v8.0.4 wifi-pumpkin**
* Virtual Machine (yes or no and which): **yes VM virtual Box**
* Operating System and version: **Kali Linux** **v3.20.2**

**Comment by timschumi** [comment]
You need to go into the VirtualBox Network Settings and enable "Bridged Adapter" instead of whatever you have selected now (I guess NAT). After that, you can select an Interface to pass to the VM (you will select your wifi interface obviously)

EDIT: If that does not work, just pass through your WiFi-Card as USB device
