### ISSUE TITLE
ARP Poisoner doesn't work

### ISSUE THREAD

**Issue by Bunder99** [P0cL4bs/WiFi-Pumpkin-deprecated#210]
Hi! I've been using your perfect tool for several weeks on Kali 2.0 Rolling 4.9.0-kali3-amd64 (fully upgraded). WiFi-Pumpkin v0.8.4 (upgraded today), wifi cards: Blueway N9000 and Alfa 036h. I cant't force to work ARP Poisoner. Scan doesn't work in proper way, because I can't see my phone connected to my wi-fi network as target. Sometimes I can see my phone, add it to target, start the attack and nothing happens. Into Wireshark I can see ARP poisoning packets, but I don't know what to do further. ARP Poisoner's log is missing, I have got no errors. How should I use ARP Poisoner properly? I can't find any instructions or wiki.
Also I have other question: can I create WiFi AP on my router TP-LINK 3600WDR (instead of WiFi dongle or wireless card) and use WiFi-pumpkin? How to do it?
Thanks for advance!

**Comment by mh4x0f** [comment]
> Scan doesn't work in proper way, because I can't see my phone connected to my wi-fi network as target. 

There's no way I can guess your network. (require more information)

> Into Wireshark I can see ARP poisoning packets, but I don't know what to do further.

of course, if you can't see your phone connected the network, there's no way to send packets for device

> How should I use ARP Poisoner properly? 

the ARP Poisoner only work without AP is mounted, because the AP already implements this. I only tested this method in Windows OS without protection.

> can I create WiFi AP on my router TP-LINK 3600WDR (instead of WiFi dongle or wireless card) and use WiFi-pumpkin? How to do it?

!["I don't understand everything"](http://images.virgula.uol.com.br/2015/11/01.gif)
