### ISSUE TITLE
2 wireless cards for WiFi-Pumpkin [Kali Linux]

### ISSUE THREAD

**Issue by alec888** [P0cL4bs/WiFi-Pumpkin-deprecated#211]
Running WiFi-Pumpkin in Kali the problem is the known 2 card error, it doesn't want to use my internal card as an internet connection provider.The program that i found that manages to do exactly this is called mitmAP but it's missing some key features can its connection setup be added to WiFi-Pumpkin?

**Comment by mh4x0f** [comment]
I'll add this options coming soon. wait..

**Comment by alec888** [comment]
was not expecting a response yet alone a positive one thanks for answering
and thank you for your work

2017-04-21 9:31 GMT-04:00 Marcos Nesster <notifications@github.com>:

**Comment by brandontict** [comment]
The creators of this project have done an **OUTSTANDING** job . And are just... AWESOME  people ! I will be donating to this project as soon as I can. 

Customers are amazed on how unsecured 802.11 can be . 

This too had help me back , while on site. 

My Panasonic toughbook has one built in WiFi card, and I have an additional USB wifi . 

Sounds like I will be able to use the internal and external one now :) Instead of having to run wifi pumpkin through a VM to solve this " issue " . 

Thank you very much!
