### ISSUE TITLE
Wifi Pumpkin & Two Wireless cards?

### ISSUE THREAD

**Issue by brandontict** [P0cL4bs/WiFi-Pumpkin-deprecated#23]
I have yet to get WiFi pumpkin to work with two wireless cards. 

I am aware that you need a local connection. 

Why cannot a external wifi card be my local connection? Or my tethered cell phone? 

Program Looks great, Beautiful GUI .

**Comment by mh4x0f** [comment]
this is not possible, because the network-manager is not have support to set card wireless in monitor mode with connection external wifi. for put the card in mode monitor it necessary to make  a "down"(Wifi disabled) for all wireless card connected the system. if you force this(use Two wireless card), you will have some conflict on connection with internet. about this, we recommend to use VM.
