### ISSUE TITLE
Wireless operation mode

### ISSUE THREAD

**Issue by nils-trubkin** [P0cL4bs/WiFi-Pumpkin-deprecated#504]
I have these buttons grayed out, even tho all dependencies are installed and working separately, am i missing something here?

![Screenshot from 2019-06-06 21-50-44](https://user-images.githubusercontent.com/32000568/59062317-d7063380-88a5-11e9-8fb9-6cdc22713a27.png)

Version used tool: 0.8.8
Virtual Machine (yes or no and which): no
Operating System and version: Kali 2019.2

**Comment by mh4x0f** [comment]
Hi, first of all, it hard for me add support for all OS to compile Mana and Karma Hostapd version, eve more so when it comes the OS Rolling release. we tools need only the binary compiled to run the wireless mode custom. btw, to enable this option only to copy the binary hostapd compiled to the folder  WiFi-Pumpkin/plugins/bin. 
<img width="509" alt="wireless folder bin " src="https://user-images.githubusercontent.com/6795613/59152438-5ddc1d00-8a1a-11e9-98d0-396e8d9c4fdc.png">

obs:
I recommend that you search on google "how to compile the hostapd Karma or Mana" and copy the binary generated to folder as you can see on screenshot above. if you make this, the options **Mana AP Mode** and **Karma AP mode** will be enable when you restart the application again. 


the wiki the hostapd mana is great look
https://github.com/sensepost/hostapd-mana/wiki

look, if you make this and everything ok, execute the local tool

> sudo python wifi-pumpkin.py

if you want to install to use the global path when the WP is installed copy the hostapd karma and mana binary to /usr/share/WiFi-Pumpkin/plugins/bin . it has necessary because many user want to change the local file and execute the tool using:

> wifi-pumpkin (call the /usr/share/WiFi-pumpkin/wifi-pumpkin.py) 

Have fun!!

**Comment by mh4x0f** [comment]
the wiki the hostapd mana is great look 
https://github.com/sensepost/hostapd-mana/wiki

**Comment by nils-trubkin** [comment]
Thank you for your reply, I will make sure to try your advice next time I'm on the machine.
