### ISSUE TITLE
Create a Debian/Ubuntu package

### ISSUE THREAD

**Issue by jonatanrdsantos** [P0cL4bs/WiFi-Pumpkin-deprecated#70]
Create a Debian/Ubuntu package for easy install in Debian based systems.

**Comment by jonatanrdsantos** [comment]
Having some problems with the external Python module to generate the deb installer

**Comment by timschumi** [comment]
I'll read a bit into the process of creating a .deb file and see if I can help

**Comment by jonatanrdsantos** [comment]
Yes, I'm having some problems with the python libraries that are not allowed to install them from the apt repository.

**Comment by timschumi** [comment]
See this: http://askubuntu.com/questions/62534/adding-post-deb-install-scripts
In this we can input the pip stuff and all the stuff we need to add.
I also recommend that we change WiFi-Pumpkin to wifi-pumpkin at the installation folder, because this follows the Debian/Ubuntu packaging recommendations and matches the program name

**Comment by timschumi** [comment]
I made a first version of a "Auto-DEB" Script: http://pastebin.com/k1B43DRn
I need to fix dependency checking though...

EDIT: Pushed first version to GitHub and opened a PR (#131). PIP dependencies are installed from the requirements.txt, the Ubuntu specific dependencies and all dependencies from apt are not checked for right now

**Comment by TimSchumi** [comment]
Should I add the make_deb.sh file to the .travis-ci.yml file?

**Comment by mh4x0f** [comment]
@TimSchumi added you contribution in about WiFi-Pumpkin [3633ef8](https://github.com/P0cL4bs/WiFi-Pumpkin/commit/3a47ae5e46f0e624a4a03991c1207268e57c21d6) thanks again :D

**Comment by timschumi** [comment]
@mh4x0f Why did you add the i386 and amd64 packages? I thought the "all" package was good for all architectures...

**Comment by mh4x0f** [comment]
@TimSchumi only by choice for download

**Comment by timschumi** [comment]
@mh4x0f I'll stick with the 'all' package, as I don't really get the difference between seperate amd64/i386 packages and the "all" package. I also recommend that if you build a deb package, that you change the Version Number in the Script for one time instead of renaming the final package. So the internal dpkg version tracking is working/you can identify the versions.

I'll add arguments to the script so that the architecture/version can be easily changed

**Comment by mh4x0f** [comment]
@TimSchumi no problem, it necessary seperate the Arch amd64 and i386 packages, because need to download correct packages in  "Depends:" and add arguments it not good ideia because the make_deb.sh only used for generate .deb. if the user want .deb he should make download on  Release.

**Comment by timschumi** [comment]
@mh4x0f When I tested it, the all package requested and installed the correct dependencies every time. And the Arguments should make it easier for you when building, because you else had to change Architecture and Version in the Script every time.
