### ISSUE TITLE
Using DBF Proxy No metasploit

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#77]
Using DBF Proxy with all setting correct no payload is being sent to target followed your video using putty. also getting this error: AP::[PumpAP] Running...
AP::BSSID::[00:c0:ca:84:49:32] CH 11
Traceback (most recent call last):
  File "/root/Desktop/WiFi-Pumpkin/Core/Main.py", line 1044, in get_bdfproxy_output
    self.dockAreaList['::bdfproxy:: '].writeModeData(str(data).split(' : ')[1])
IndexError: list index out of range

![image](https://cloud.githubusercontent.com/assets/20466541/18024016/4c138d86-6bcf-11e6-9827-0459fcf0b408.png)

**Comment by mh4x0f** [comment]
try again,  send me output if it worked...

**Comment by Cosmic4x2** [comment]
did not work.

**Comment by mh4x0f** [comment]
send me screenshot of terminal

**Comment by Cosmic4x2** [comment]
[image: Inline image 1]

**Comment by mh4x0f** [comment]
I checking this

**Comment by mh4x0f** [comment]
hi, everything ok with BDFproxy. I did some test in my Lab the problem is putty.org the website when started download putty.exe the request come from https:the.earth.li/~sgtatham/putty/latest/x86/putty.exe the BDFproxy not intercept HTTPS request , only  request HTTP (text plain). thank's for issue the commit above solved the bug... :D

**Comment by mh4x0f** [comment]
you can you try redownloading it, but in this section bellow. this  Putty listed is text plain (HTTP protocol).
![screenshot_kali10kkkkk](https://cloud.githubusercontent.com/assets/6795613/18024810/01a3546e-6bea-11e6-8240-6a053a6ef9aa.png)

**Comment by Cosmic4x2** [comment]
yes it worked...

Thx
